/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.LinkedList;
import java.util.StringJoiner;

public class Restaurant {

    LinkedList<Reviews> restaurantsReviews = new LinkedList<>();
    public String name;
    public int stars;
    public int priceCategory;


    public Restaurant(String name, int stars, int priceCategory) {
        this.name = name;
        this.stars = stars;
        this.priceCategory = priceCategory;
    }

    public int addReview(Reviews review){
        restaurantsReviews.add(review);

        double starCounter = 0;
        double average;

        for(Reviews reviews: restaurantsReviews){
            starCounter += reviews.numberOfStars;
        }

        average = starCounter / restaurantsReviews.size();
        this.stars = (int) average;
        return (int) average;

//        starCounter += review.numberOfStars;
    }


    public String toString(){
//        StringJoiner restaurants = new StringJoiner("\n");
        return String.format("Restaurant: %s, Price: %d", this.name, this.stars, this.priceCategory);

    }
}
