/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;

import static org.junit.Assert.*;

public class AppTest {

    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();

    @Before
    public void setUpStreams() {
        System.setOut(new PrintStream(outContent));
    }

    @Test
    public void testFileGate() {
        File path = new File("./src/main/resources/gate.js");
        assertNotNull("app should have a greeting", outContent);
    }
}
