/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void rollTest(){
        int[] rollDice = new int[4];
        int diceLength = rollDice.length;
        assertEquals("This is the number of times the dice rolled", diceLength,Library.roll(4).length
        );
    }
    @Test public void testContainsDuplicates(){
        int[] findDuplicates = new int[]{2,4,6,6,8};
        assertTrue("This checks for any duplicate values", Library.containsDuplicates(findDuplicates));
    }
    @Test public void testCalculateAverage(){
        int[] findAverage = new int[]{3,5,7,19};
        double theAverage = Library.calculateAverage(findAverage);
        assertTrue("The average value for this array is", theAverage == 8.5);
    }
    @Test public void testCalculateAverageArrays(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
//        int[] expecting = new int[] {55, 54, 60, 53, 59, 57, 61};
        String expecting = Arrays.toString(weeklyMonthTemperatures[2]);
        String result = Library.averageArrayValue(weeklyMonthTemperatures);
        assertEquals(result, expecting);
    }

}
